name: Run Daily Options Screener

on:
  workflow_dispatch:
  schedule:
    - cron: '5 21 * * 1-5'

jobs:
  run-screener:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install Python dependencies
        run: pip install -r requirements.txt

      - name: Run Options Screener
        env:
          ALPACA_KEY: ${{ secrets.ALPACA_KEY }}
          ALPACA_SECRET: ${{ secrets.ALPACA_SECRET }}
          PUSHBULLET_API_KEY: ${{ secrets.PUSHBULLET_API_KEY }}
        # FINAL FIX: Use the full path to the Python that has the libraries installed
        run: ${{ env.pythonLocation }}/bin/python -u main.py
